name: film
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.5
  - pytorch=1.0.1
  - torchvision==0.2.1
  - cudatoolkit==9.0
  - numpy=1.15
  - scipy==1.0.0
  - pillow
  - h5py
  - scikit-learn=0.19
  - tqdm
  - termcolor
  - ipdb
