name: film
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pytorch=1.0.1
  - torchvision==0.2.1
  - cudatoolkit==9.0
  - jupyterlab=0.35
  - numpy=1.15
  - jupyter
  - scipy
  - pillow
  - h5py
  - pip:
    - nbmerge
    - pytest-xdist
